### ISSUE TITLE
访问登录页面报错

### ISSUE THREAD

**Issue by zjw186** [moz-kamen/keycloak-login-spi#3]
你好，按照您写的步骤配置完成后，访问登录界面报错，
![image](https://user-images.githubusercontent.com/17307064/122632469-8b79f780-d105-11eb-92f9-f0c04ca6d064.png)
是需要修改freemarker模板吗？

**Comment by moz-kamen** [comment]
> 你好，按照您写的步骤配置完成后，访问登录界面报错，
> ![image](https://user-images.githubusercontent.com/17307064/122632469-8b79f780-d105-11eb-92f9-f0c04ca6d064.png)
> 是需要修改freemarker模板吗？

这个 spi 中提供的 Custom Login Authenticator 中包含的几个 Authenticator
相当于是对 oauth2 中 grant_type 为 possword 的鉴权方式进行的一个拓展
新增了 login_type 字段，来区分介绍中的几种登陆方式，提供不同的入参字段和处理逻辑

从你问题中我觉得你想要使用的登陆方式应该是 keycloak 的 “browser” authentication flow
这部分还是 keycloak 原本提供的功能，如果有报错，请先试着在不引入或配置该 spi 的情况下对着 keycloak 官方文档尝试一下
当你把 authentication flow 修改为 spi 中提供的部件时，才会生效

**Comment by moz-kamen** [comment]
请参考 readme 中流程进行配置，理解该 spi 拓展的功能模块
与原有的 “browser” authentication flow 应该是互不冲突的
